import { createHash } from 'node:crypto';
export const VOXCPM_MODEL_ID = 'openbmb/VoxCPM2';
export const VOXCPM_MODEL_REVISION = 'bffb3df5a29440629464e5e839f4d214c8714c3d';
export const AUDIO_DISCLOSURE_VERSION = 'ai-voice-notice-1';
export const AUDIO_RENDER_VERSION = 'voxcpm2-voice-a-provenance-2';
export const sha256 = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
export interface AudioIdentity {
  modelId: string; modelRevision: string; presetSha256: string; referenceSha256: string;
  disclosureVersion: string; renderVersion: string;
}
export function audioDisclosure(language: string): string {
  if (language === 'en') return 'This experimental audio guide uses a voice generated by artificial intelligence.';
  if (language === 'de') return 'Dieser experimentelle Audioguide verwendet eine durch künstliche Intelligenz erzeugte Stimme.';
  if (language === 'it') return 'Questa audioguida sperimentale utilizza una voce generata dall’intelligenza artificiale.';
  if (language === 'fr') return 'Cet audioguide expérimental utilise une voix générée par intelligence artificielle.';
  if (language === 'es') return 'Esta audioguía experimental utiliza una voz generada por inteligencia artificial.';
  throw new Error('AUDIO_LANGUAGE_UNSUPPORTED');
}
/** Identity of one rendering setup: part of every audio hash, so changing a voice file or the engine invalidates its audio. */
export const rendererKeyOf = (identity: AudioIdentity): string => sha256('nano-vllm-voxcpm-2.0.4-tempo-v1:' + JSON.stringify(identity));
export function audioIdentity(preset: Buffer, reference: Buffer): AudioIdentity {
  const config = JSON.parse(preset.toString('utf8')) as { modelRevision?: string; modelId?: string; renderVersion?: string };
  const modelId = config.modelId ?? VOXCPM_MODEL_ID;
  const modelRevision = config.modelRevision ?? VOXCPM_MODEL_REVISION;
  if (modelId !== VOXCPM_MODEL_ID || !/^[0-9a-f]{40}$/.test(modelRevision)) throw new Error('Invalid voice model identity');
  const renderVersion = config.renderVersion ?? AUDIO_RENDER_VERSION;
  if (!/^voxcpm2-voice-a-provenance-\d+$/.test(renderVersion)) throw new Error('Invalid audio render version');
  return { modelId, modelRevision, presetSha256: sha256(preset), referenceSha256: sha256(reference),
    disclosureVersion: AUDIO_DISCLOSURE_VERSION, renderVersion };
}
