const en = {
  introduction: 'Introduction', firstStop: 'Go to the first stop', introductionPending: 'The introduction audio is being prepared.',
  welcome: 'Welcome to the tour',
  experimental: 'Experimental prototype · Text and voice generated with AI', beforeStarting: 'Explore at your own pace',
  safety: 'The route is a guide for your walk. Follow local signs and access rules, and pause somewhere safe when checking your phone.',
  locationChoice: 'Sharing your location is optional. Photos come from Wikimedia and maps from OpenStreetMap.',
  startSafely: 'Understood, start', rememberNotice: 'We’ll remember this notice in this browser.', aiVoice: 'Voice generated with AI', aboutVoice: 'About this voice',
  aboutTour: 'Tour information', humanReviewed: 'Reviewed by a person on',
  stopLocation: 'Stop using my location', externalMap: 'Google Maps opens an external service with the selected destination.',
  reportIssue: 'Report a problem',
  back: 'Back', stop: 'Stop', of: 'of', stops: 'Stops', photos: 'Photos', story: 'Text', map: 'Map', mapOptions: 'Map options',
  current: 'Current stop', listened: 'Listened', partial: 'Partway through', pending: 'Ready to discover',
  play: 'Play narration', pause: 'Pause narration', seek: 'Audio progress', rewind: 'Back 15 seconds', forward: 'Forward 15 seconds',
  loadingAudio: 'Loading audio…', audioError: 'Audio could not be loaded.', retry: 'Try again',
  audioPending: 'This stop’s audio is not ready yet.', preparing: 'Preparing your audio…', checking: 'Finding your audio…', prepare: 'Prepare audio',
  unavailable: 'Audio is not available in this language yet.', photoMissing: 'Take a moment to look around.',
  photoHint: 'The story continues in your headphones.', previousPhoto: 'Previous photo', nextPhoto: 'Next photo',
  credits: 'Photo credits', next: 'Next stop', directions: 'Open in Maps',
  destination: 'Walk to', chooseDestination: 'Choose destination', finished: 'Stop listened',
  tourFinished: 'You have listened to the whole tour.', routeEnd: 'Last stop of the route.',
  tours: 'Back to tours', locating: 'Finding your location…', locate: 'Show my location',
  locationDenied: 'Location is off. You can still open directions.', locationMissing: 'Your location is unavailable right now.',
  routeLoading: 'Loading route…', routeError: 'Route unavailable. Stops are still shown.', walk: 'walking',
  yourLocation: 'Your location', mapLabel: 'Tour map', noMap: 'Map unavailable.', empty: 'No stops in this tour yet.',
  centerOnMe: 'Center on me', walkingRoute: 'Walking route', fixMap: 'Fix the map', published: 'Published', privateReview: 'In private review',
  more: 'More', share: 'Share this walk', linkCopied: 'Link copied', openAppleMaps: 'Open in Apple Maps', playbackSpeed: 'Playback speed',
  locationHelp: 'To turn it on, allow location for this site in your browser settings.', accuracy: 'Accuracy',
  safetyShort: 'Follow local signs and pause somewhere safe to look at your phone.', resumeAt: 'Continue at', startAt: 'Start the walk',
  seeSummary: 'See your walk summary', stopsListened: (n: number, total: number) => `${n} of ${total} stops listened to`, walkedApprox: (distance: string) => `About ${distance} walked`,
  otherWalks: (city: string) => `More walks in ${city}`, sourcesTitle: 'Sources and credits', closeSummary: 'Close',
};
const es: typeof en = {
  introduction: 'Introducción', firstStop: 'Ir a la primera parada', introductionPending: 'Se está preparando el audio de la introducción.',
  welcome: 'Bienvenida al tour',
  experimental: 'Prototipo experimental · Texto y voz generados con IA', beforeStarting: 'Tu paseo, a tu ritmo',
  safety: 'La ruta te orienta durante el paseo. Sigue las señales y respeta los accesos del lugar; para mirar el móvil, haz una pausa en un sitio seguro.',
  locationChoice: 'Tu ubicación es opcional. Las fotos vienen de Wikimedia y los mapas de OpenStreetMap.',
  startSafely: 'Entendido, empezar', rememberNotice: 'Recordaremos este aviso en este navegador.', aiVoice: 'Voz generada por IA', aboutVoice: 'Sobre esta voz',
  aboutTour: 'Información del tour', humanReviewed: 'Revisado por una persona el',
  stopLocation: 'Dejar de usar mi ubicación', externalMap: 'Google Maps abre un servicio externo con el destino seleccionado.',
  reportIssue: 'Informar de un problema',
  back: 'Volver', stop: 'Parada', of: 'de', stops: 'Paradas', photos: 'Fotos', story: 'Texto', map: 'Mapa', mapOptions: 'Opciones del mapa',
  current: 'Parada actual', listened: 'Escuchada', partial: 'A medias', pending: 'Por descubrir',
  play: 'Reproducir narración', pause: 'Pausar narración', seek: 'Progreso del audio', rewind: 'Retroceder 15 segundos', forward: 'Avanzar 15 segundos',
  loadingAudio: 'Cargando audio…', audioError: 'No se pudo cargar el audio.', retry: 'Reintentar',
  audioPending: 'El audio de esta parada aún no está listo.', preparing: 'Preparando tu audio…', checking: 'Buscando tu audio…', prepare: 'Preparar audio',
  unavailable: 'El audio aún no está disponible en este idioma.', photoMissing: 'Mira a tu alrededor.',
  photoHint: 'La historia continúa en tus auriculares.', previousPhoto: 'Foto anterior', nextPhoto: 'Foto siguiente',
  credits: 'Créditos de la foto', next: 'Siguiente parada', directions: 'Abrir en Mapas',
  destination: 'Caminar hasta', chooseDestination: 'Elegir destino', finished: 'Parada escuchada',
  tourFinished: 'Has escuchado todo el tour.', routeEnd: 'Última parada del recorrido.',
  tours: 'Volver a los tours', locating: 'Buscando tu ubicación…', locate: 'Mostrar mi ubicación',
  locationDenied: 'La ubicación está desactivada. Puedes abrir las indicaciones.', locationMissing: 'Tu ubicación no está disponible ahora.',
  routeLoading: 'Cargando recorrido…', routeError: 'Recorrido no disponible. Puedes ver las paradas.', walk: 'a pie',
  yourLocation: 'Tu ubicación', mapLabel: 'Mapa del tour', noMap: 'Mapa no disponible.', empty: 'Este tour aún no tiene paradas.',
  centerOnMe: 'Centrar en mí', walkingRoute: 'Ruta a pie', fixMap: 'Corregir el mapa', published: 'Publicado', privateReview: 'En revisión privada',
  more: 'Más', share: 'Compartir paseo', linkCopied: 'Enlace copiado', openAppleMaps: 'Abrir en Apple Maps', playbackSpeed: 'Velocidad de reproducción',
  locationHelp: 'Para activarla, permite la ubicación de este sitio en los ajustes del navegador.', accuracy: 'Precisión',
  safetyShort: 'Sigue las señales y haz una pausa en un sitio seguro para mirar el móvil.', resumeAt: 'Continuar en', startAt: 'Empezar el paseo',
  seeSummary: 'Ver el resumen del paseo', stopsListened: (n, total) => `${n} de ${total} paradas escuchadas`, walkedApprox: distance => `Unos ${distance} recorridos`,
  otherWalks: city => `Otros paseos en ${city}`, sourcesTitle: 'Fuentes y créditos', closeSummary: 'Cerrar',
};
const fr: typeof en = {
  introduction: 'Introduction', firstStop: 'Aller à la première étape', introductionPending: 'L’audio de l’introduction est en préparation.',
  welcome: 'Bienvenue dans cette visite',
  experimental: 'Prototype expérimental · Texte et voix générés par IA', beforeStarting: 'Votre balade, à votre rythme',
  safety: 'Le parcours vous guide pendant la balade. Suivez la signalisation et respectez les accès autorisés ; faites une pause dans un endroit sûr pour consulter votre téléphone.',
  locationChoice: 'Partager votre position est facultatif. Les photos viennent de Wikimedia et les cartes d’OpenStreetMap.',
  startSafely: 'Compris, commencer', rememberNotice: 'Ce navigateur mémorisera que vous avez vu ces informations.', aiVoice: 'Voix générée par IA', aboutVoice: 'À propos de cette voix',
  aboutTour: 'Informations sur la visite', humanReviewed: 'Révisé par une personne le',
  stopLocation: 'Arrêter la localisation', externalMap: 'Google Maps ouvre un service externe avec la destination choisie.',
  reportIssue: 'Signaler un problème',
  back: 'Retour', stop: 'Étape', of: 'sur', stops: 'Étapes', photos: 'Photos', story: 'Texte', map: 'Carte', mapOptions: 'Options de la carte',
  current: 'Étape actuelle', listened: 'Écoutée', partial: 'En cours', pending: 'À découvrir',
  play: 'Écouter le récit', pause: 'Mettre en pause', seek: 'Progression audio', rewind: 'Reculer de 15 secondes', forward: 'Avancer de 15 secondes',
  loadingAudio: 'Chargement audio…', audioError: 'Impossible de charger l’audio.', retry: 'Réessayer',
  audioPending: 'L’audio de cette étape n’est pas encore prêt.', preparing: 'Préparation de votre audio…', checking: 'Recherche de votre audio…', prepare: 'Préparer l’audio',
  unavailable: 'L’audio n’est pas encore disponible dans cette langue.', photoMissing: 'Regardez autour de vous.',
  photoHint: 'L’histoire continue dans vos écouteurs.', previousPhoto: 'Photo précédente', nextPhoto: 'Photo suivante',
  credits: 'Crédits photo', next: 'Étape suivante', directions: 'Ouvrir Maps',
  destination: 'Marcher vers', chooseDestination: 'Choisir la destination', finished: 'Étape écoutée',
  tourFinished: 'Vous avez écouté toute la visite.', routeEnd: 'Dernière étape du parcours.',
  tours: 'Retour aux visites', locating: 'Recherche de votre position…', locate: 'Afficher ma position',
  locationDenied: 'La localisation est désactivée. L’itinéraire reste accessible.', locationMissing: 'Votre position est indisponible pour le moment.',
  routeLoading: 'Chargement du parcours…', routeError: 'Parcours indisponible. Les étapes restent visibles.', walk: 'à pied',
  yourLocation: 'Votre position', mapLabel: 'Carte de la visite', noMap: 'Carte indisponible.', empty: 'Cette visite ne contient pas encore d’étapes.',
  centerOnMe: 'Me centrer', walkingRoute: 'Itinéraire à pied', fixMap: 'Corriger la carte', published: 'Publié', privateReview: 'En révision privée',
  more: 'Plus', share: 'Partager la balade', linkCopied: 'Lien copié', openAppleMaps: 'Ouvrir dans Plans', playbackSpeed: 'Vitesse de lecture',
  locationHelp: 'Pour l’activer, autorisez la localisation de ce site dans les réglages du navigateur.', accuracy: 'Précision',
  safetyShort: 'Suivez la signalisation et faites une pause dans un endroit sûr pour consulter votre téléphone.', resumeAt: 'Reprendre à', startAt: 'Commencer la balade',
  seeSummary: 'Voir le résumé de la balade', stopsListened: (n, total) => `${n} étapes sur ${total} écoutées`, walkedApprox: distance => `Environ ${distance} parcourus`,
  otherWalks: city => `Autres balades à ${city}`, sourcesTitle: 'Sources et crédits', closeSummary: 'Fermer',
};
const de: typeof en = {
  introduction: 'Einführung', firstStop: 'Zur ersten Station', introductionPending: 'Das Audio der Einführung wird vorbereitet.',
  welcome: 'Willkommen zum Rundgang',
  experimental: 'Experimenteller Prototyp · Text und Stimme mit KI erzeugt', beforeStarting: 'Dein Rundgang, in deinem Tempo',
  safety: 'Die Route ist eine Orientierung für deinen Spaziergang. Beachte Schilder und Zugangsregeln und mach eine Pause an einem sicheren Ort, wenn du aufs Handy schaust.',
  locationChoice: 'Das Teilen deines Standorts ist freiwillig. Die Fotos stammen von Wikimedia, die Karten von OpenStreetMap.',
  startSafely: 'Verstanden, los geht’s', rememberNotice: 'Wir merken uns diesen Hinweis in diesem Browser.', aiVoice: 'Mit KI erzeugte Stimme', aboutVoice: 'Über diese Stimme',
  aboutTour: 'Informationen zum Rundgang', humanReviewed: 'Von einer Person geprüft am',
  stopLocation: 'Meinen Standort nicht mehr verwenden', externalMap: 'Google Maps öffnet einen externen Dienst mit dem gewählten Ziel.',
  reportIssue: 'Problem melden',
  back: 'Zurück', stop: 'Station', of: 'von', stops: 'Stationen', photos: 'Fotos', story: 'Text', map: 'Karte', mapOptions: 'Kartenoptionen',
  current: 'Aktuelle Station', listened: 'Gehört', partial: 'Teilweise gehört', pending: 'Noch zu entdecken',
  play: 'Erzählung abspielen', pause: 'Erzählung pausieren', seek: 'Audiofortschritt', rewind: '15 Sekunden zurück', forward: '15 Sekunden vor',
  loadingAudio: 'Audio wird geladen…', audioError: 'Das Audio konnte nicht geladen werden.', retry: 'Erneut versuchen',
  audioPending: 'Das Audio dieser Station ist noch nicht bereit.', preparing: 'Dein Audio wird vorbereitet…', checking: 'Dein Audio wird gesucht…', prepare: 'Audio vorbereiten',
  unavailable: 'Audio ist in dieser Sprache noch nicht verfügbar.', photoMissing: 'Schau dich um.',
  photoHint: 'Die Geschichte geht in deinen Kopfhörern weiter.', previousPhoto: 'Vorheriges Foto', nextPhoto: 'Nächstes Foto',
  credits: 'Bildnachweise', next: 'Nächste Station', directions: 'In Karten öffnen',
  destination: 'Gehe zu', chooseDestination: 'Ziel wählen', finished: 'Station gehört',
  tourFinished: 'Du hast den ganzen Rundgang gehört.', routeEnd: 'Letzte Station der Route.',
  tours: 'Zurück zu den Rundgängen', locating: 'Standort wird gesucht…', locate: 'Meinen Standort anzeigen',
  locationDenied: 'Der Standort ist aus. Du kannst trotzdem die Wegbeschreibung öffnen.', locationMissing: 'Dein Standort ist gerade nicht verfügbar.',
  routeLoading: 'Route wird geladen…', routeError: 'Route nicht verfügbar. Die Stationen bleiben sichtbar.', walk: 'zu Fuß',
  yourLocation: 'Dein Standort', mapLabel: 'Karte des Rundgangs', noMap: 'Karte nicht verfügbar.', empty: 'Dieser Rundgang hat noch keine Stationen.',
  centerOnMe: 'Auf mich zentrieren', walkingRoute: 'Fußweg', fixMap: 'Karte verbessern', published: 'Veröffentlicht', privateReview: 'In privater Prüfung',
  more: 'Mehr', share: 'Rundgang teilen', linkCopied: 'Link kopiert', openAppleMaps: 'In Apple Karten öffnen', playbackSpeed: 'Wiedergabegeschwindigkeit',
  locationHelp: 'Zum Einschalten erlaube den Standort für diese Website in den Browsereinstellungen.', accuracy: 'Genauigkeit',
  safetyShort: 'Beachte Schilder und mach eine Pause an einem sicheren Ort, wenn du aufs Handy schaust.', resumeAt: 'Weiter bei', startAt: 'Rundgang beginnen',
  seeSummary: 'Zusammenfassung ansehen', stopsListened: (n, total) => `${n} von ${total} Stationen gehört`, walkedApprox: distance => `Etwa ${distance} gegangen`,
  otherWalks: city => `Weitere Rundgänge in ${city}`, sourcesTitle: 'Quellen und Nachweise', closeSummary: 'Schließen',
};
const it: typeof en = {
  introduction: 'Introduzione', firstStop: 'Vai alla prima tappa', introductionPending: 'L’audio dell’introduzione è in preparazione.',
  welcome: 'Benvenuto al tour',
  experimental: 'Prototipo sperimentale · Testo e voce generati con IA', beforeStarting: 'La tua passeggiata, al tuo ritmo',
  safety: 'Il percorso ti orienta durante la passeggiata. Segui la segnaletica, rispetta gli accessi del luogo e fermati in un posto sicuro per guardare il telefono.',
  locationChoice: 'Condividere la posizione è facoltativo. Le foto provengono da Wikimedia e le mappe da OpenStreetMap.',
  startSafely: 'Ho capito, iniziamo', rememberNotice: 'Ricorderemo questo avviso in questo browser.', aiVoice: 'Voce generata con IA', aboutVoice: 'Informazioni su questa voce',
  aboutTour: 'Informazioni sul tour', humanReviewed: 'Rivisto da una persona il',
  stopLocation: 'Smetti di usare la mia posizione', externalMap: 'Google Maps apre un servizio esterno con la destinazione scelta.',
  reportIssue: 'Segnala un problema',
  back: 'Indietro', stop: 'Tappa', of: 'di', stops: 'Tappe', photos: 'Foto', story: 'Testo', map: 'Mappa', mapOptions: 'Opzioni della mappa',
  current: 'Tappa attuale', listened: 'Ascoltata', partial: 'A metà', pending: 'Da scoprire',
  play: 'Riproduci la narrazione', pause: 'Metti in pausa la narrazione', seek: 'Avanzamento audio', rewind: 'Indietro di 15 secondi', forward: 'Avanti di 15 secondi',
  loadingAudio: 'Caricamento audio…', audioError: 'Impossibile caricare l’audio.', retry: 'Riprova',
  audioPending: 'L’audio di questa tappa non è ancora pronto.', preparing: 'Preparazione del tuo audio…', checking: 'Ricerca del tuo audio…', prepare: 'Prepara l’audio',
  unavailable: 'L’audio non è ancora disponibile in questa lingua.', photoMissing: 'Guardati intorno.',
  photoHint: 'La storia continua nelle tue cuffie.', previousPhoto: 'Foto precedente', nextPhoto: 'Foto successiva',
  credits: 'Crediti fotografici', next: 'Prossima tappa', directions: 'Apri in Mappe',
  destination: 'Cammina fino a', chooseDestination: 'Scegli la destinazione', finished: 'Tappa ascoltata',
  tourFinished: 'Hai ascoltato tutto il tour.', routeEnd: 'Ultima tappa del percorso.',
  tours: 'Torna ai tour', locating: 'Ricerca della posizione…', locate: 'Mostra la mia posizione',
  locationDenied: 'La posizione è disattivata. Puoi comunque aprire le indicazioni.', locationMissing: 'La tua posizione non è disponibile in questo momento.',
  routeLoading: 'Caricamento del percorso…', routeError: 'Percorso non disponibile. Le tappe restano visibili.', walk: 'a piedi',
  yourLocation: 'La tua posizione', mapLabel: 'Mappa del tour', noMap: 'Mappa non disponibile.', empty: 'Questo tour non ha ancora tappe.',
  centerOnMe: 'Centra su di me', walkingRoute: 'Percorso a piedi', fixMap: 'Correggi la mappa', published: 'Pubblicato', privateReview: 'In revisione privata',
  more: 'Altro', share: 'Condividi il tour', linkCopied: 'Link copiato', openAppleMaps: 'Apri in Mappe', playbackSpeed: 'Velocità di riproduzione',
  locationHelp: 'Per attivarla, consenti la posizione per questo sito nelle impostazioni del browser.', accuracy: 'Precisione',
  safetyShort: 'Segui la segnaletica e fermati in un posto sicuro per guardare il telefono.', resumeAt: 'Continua da', startAt: 'Inizia il percorso',
  seeSummary: 'Vedi il riepilogo del percorso', stopsListened: (n, total) => `${n} tappe su ${total} ascoltate`, walkedApprox: distance => `Circa ${distance} percorsi`,
  otherWalks: city => `Altri percorsi a ${city}`, sourcesTitle: 'Fonti e crediti', closeSummary: 'Chiudi',
};
export function listeningCopy(language: string) {
  if (language === 'es') return es;
  if (language === 'fr') return fr;
  if (language === 'de') return de;
  if (language === 'it') return it;
  return en;
}
