const en = {
  introduction: 'Introduction', firstStop: 'Go to the first stop', introductionPending: 'The introduction audio is being prepared.',
  welcome: 'Welcome to the tour', enterTour: 'Go to the tour',
  experimental: 'Experimental prototype · Text and voice generated with AI', beforeStarting: 'Explore at your own pace',
  safety: 'The route is a guide for your walk. Follow local signs and access rules, and pause somewhere safe when checking your phone.',
  locationChoice: 'Sharing your location is optional. Photos come from Wikimedia and maps from OpenStreetMap.',
  startSafely: 'Understood, start', rememberNotice: 'We’ll remember this notice in this browser.', aiVoice: 'Voice generated with AI', aboutVoice: 'About this voice',
  aboutTour: 'Tour information', humanReviewed: 'Reviewed by a person on', withoutLocation: 'Continue without location',
  stopLocation: 'Stop using my location', externalMap: 'Google Maps opens an external service with the selected destination.',
  reportIssue: 'Report a problem',
  back: 'Back', stop: 'Stop', of: 'of', stops: 'Stops', photos: 'Photos', story: 'Text', map: 'Map', mapOptions: 'Map options',
  current: 'Current stop', listened: 'Listened', partial: 'Partway through', pending: 'Ready to discover',
  play: 'Play narration', pause: 'Pause narration', seek: 'Audio progress', rewind: 'Back 15 seconds', forward: 'Forward 15 seconds',
  loadingAudio: 'Loading audio…', audioError: 'Audio could not be loaded.', retry: 'Try again',
  audioPending: 'This stop’s audio is not ready yet.', preparing: 'Preparing your audio…', checking: 'Finding your audio…', prepare: 'Prepare audio',
  unavailable: 'Audio is not available in this language yet.', photoMissing: 'Take a moment to look around.',
  photoHint: 'The story continues in your headphones.', previousPhoto: 'Previous photo', nextPhoto: 'Next photo',
  credits: 'Photo credits', next: 'Next stop', directions: 'Open in Maps',
  destination: 'Walk to', chooseDestination: 'Choose destination', finished: 'Stop listened',
  tourFinished: 'You have listened to the whole tour.', routeEnd: 'Last stop of the route.',
  tours: 'Back to tours', locating: 'Finding your location…', locate: 'Show my location',
  locationDenied: 'Location is off. You can still open directions.', locationMissing: 'Your location is unavailable right now.',
  routeLoading: 'Loading route…', routeError: 'Route unavailable. Stops are still shown.', walk: 'walking',
  yourLocation: 'Your location', mapLabel: 'Tour map', noMap: 'Map unavailable.', empty: 'No stops in this tour yet.',
};
const es: typeof en = {
  introduction: 'Introducción', firstStop: 'Ir a la primera parada', introductionPending: 'Se está preparando el audio de la introducción.',
  welcome: 'Bienvenida al tour', enterTour: 'Ir al recorrido',
  experimental: 'Prototipo experimental · Texto y voz generados con IA', beforeStarting: 'Tu paseo, a tu ritmo',
  safety: 'La ruta te orienta durante el paseo. Sigue las señales y respeta los accesos del lugar; para mirar el móvil, haz una pausa en un sitio seguro.',
  locationChoice: 'Tu ubicación es opcional. Las fotos vienen de Wikimedia y los mapas de OpenStreetMap.',
  startSafely: 'Entendido, empezar', rememberNotice: 'Recordaremos este aviso en este navegador.', aiVoice: 'Voz generada por IA', aboutVoice: 'Sobre esta voz',
  aboutTour: 'Información del tour', humanReviewed: 'Revisado por una persona el', withoutLocation: 'Continuar sin ubicación',
  stopLocation: 'Dejar de usar mi ubicación', externalMap: 'Google Maps abre un servicio externo con el destino seleccionado.',
  reportIssue: 'Informar de un problema',
  back: 'Volver', stop: 'Parada', of: 'de', stops: 'Paradas', photos: 'Fotos', story: 'Texto', map: 'Mapa', mapOptions: 'Opciones del mapa',
  current: 'Parada actual', listened: 'Escuchada', partial: 'A medias', pending: 'Por descubrir',
  play: 'Reproducir narración', pause: 'Pausar narración', seek: 'Progreso del audio', rewind: 'Retroceder 15 segundos', forward: 'Avanzar 15 segundos',
  loadingAudio: 'Cargando audio…', audioError: 'No se pudo cargar el audio.', retry: 'Reintentar',
  audioPending: 'El audio de esta parada aún no está listo.', preparing: 'Preparando tu audio…', checking: 'Buscando tu audio…', prepare: 'Preparar audio',
  unavailable: 'El audio aún no está disponible en este idioma.', photoMissing: 'Mira a tu alrededor.',
  photoHint: 'La historia continúa en tus auriculares.', previousPhoto: 'Foto anterior', nextPhoto: 'Foto siguiente',
  credits: 'Créditos de la foto', next: 'Siguiente parada', directions: 'Abrir en Mapas',
  destination: 'Caminar hasta', chooseDestination: 'Elegir destino', finished: 'Parada escuchada',
  tourFinished: 'Has escuchado todo el tour.', routeEnd: 'Última parada del recorrido.',
  tours: 'Volver a los tours', locating: 'Buscando tu ubicación…', locate: 'Mostrar mi ubicación',
  locationDenied: 'La ubicación está desactivada. Puedes abrir las indicaciones.', locationMissing: 'Tu ubicación no está disponible ahora.',
  routeLoading: 'Cargando recorrido…', routeError: 'Recorrido no disponible. Puedes ver las paradas.', walk: 'a pie',
  yourLocation: 'Tu ubicación', mapLabel: 'Mapa del tour', noMap: 'Mapa no disponible.', empty: 'Este tour aún no tiene paradas.',
};
const fr: typeof en = {
  introduction: 'Introduction', firstStop: 'Aller à la première étape', introductionPending: 'L’audio de l’introduction est en préparation.',
  welcome: 'Bienvenue dans cette visite', enterTour: 'Accéder au parcours',
  experimental: 'Prototype expérimental · Texte et voix générés par IA', beforeStarting: 'Votre balade, à votre rythme',
  safety: 'Le parcours vous guide pendant la balade. Suivez la signalisation et respectez les accès autorisés ; faites une pause dans un endroit sûr pour consulter votre téléphone.',
  locationChoice: 'Partager votre position est facultatif. Les photos viennent de Wikimedia et les cartes d’OpenStreetMap.',
  startSafely: 'Compris, commencer', rememberNotice: 'Ce navigateur mémorisera que vous avez vu ces informations.', aiVoice: 'Voix générée par IA', aboutVoice: 'À propos de cette voix',
  aboutTour: 'Informations sur la visite', humanReviewed: 'Révisé par une personne le', withoutLocation: 'Continuer sans localisation',
  stopLocation: 'Arrêter la localisation', externalMap: 'Google Maps ouvre un service externe avec la destination choisie.',
  reportIssue: 'Signaler un problème',
  back: 'Retour', stop: 'Étape', of: 'sur', stops: 'Étapes', photos: 'Photos', story: 'Texte', map: 'Carte', mapOptions: 'Options de la carte',
  current: 'Étape actuelle', listened: 'Écoutée', partial: 'En cours', pending: 'À découvrir',
  play: 'Écouter le récit', pause: 'Mettre en pause', seek: 'Progression audio', rewind: 'Reculer de 15 secondes', forward: 'Avancer de 15 secondes',
  loadingAudio: 'Chargement audio…', audioError: 'Impossible de charger l’audio.', retry: 'Réessayer',
  audioPending: 'L’audio de cette étape n’est pas encore prêt.', preparing: 'Préparation de votre audio…', checking: 'Recherche de votre audio…', prepare: 'Préparer l’audio',
  unavailable: 'L’audio n’est pas encore disponible dans cette langue.', photoMissing: 'Regardez autour de vous.',
  photoHint: 'L’histoire continue dans vos écouteurs.', previousPhoto: 'Photo précédente', nextPhoto: 'Photo suivante',
  credits: 'Crédits photo', next: 'Étape suivante', directions: 'Ouvrir Maps',
  destination: 'Marcher vers', chooseDestination: 'Choisir la destination', finished: 'Étape écoutée',
  tourFinished: 'Vous avez écouté toute la visite.', routeEnd: 'Dernière étape du parcours.',
  tours: 'Retour aux visites', locating: 'Recherche de votre position…', locate: 'Afficher ma position',
  locationDenied: 'La localisation est désactivée. L’itinéraire reste accessible.', locationMissing: 'Votre position est indisponible pour le moment.',
  routeLoading: 'Chargement du parcours…', routeError: 'Parcours indisponible. Les étapes restent visibles.', walk: 'à pied',
  yourLocation: 'Votre position', mapLabel: 'Carte de la visite', noMap: 'Carte indisponible.', empty: 'Cette visite ne contient pas encore d’étapes.',
};
export function listeningCopy(language: string) {
  if (language === 'es') return es;
  if (language === 'fr') return fr;
  if (language === 'de') return { ...en, welcome: 'Willkommen zum Rundgang', enterTour: 'Zum Rundgang', introduction: 'Einführung', firstStop: 'Zur ersten Station', introductionPending: 'Das Audio der Einführung wird vorbereitet.' };
  if (language === 'it') return { ...en, welcome: 'Benvenuto al tour', enterTour: 'Vai al percorso', introduction: 'Introduzione', firstStop: 'Vai alla prima tappa', introductionPending: 'L’audio dell’introduzione è in preparazione.' };
  return en;
}
