import type { Language } from '@/types/api';

const es = {
  heading: 'La ciudad tiene mucho que contarte.',
  intro: 'Elige un paseo. Ponte los auriculares. Descubre lo que suele pasar desapercibido.',
  search: '¿Dónde quieres pasear?',
  featured: 'Una ciudad, otra mirada',
  allCities: 'Todas',
  cities: 'Ciudades disponibles',
  walkingTour: 'Paseo con audio',
  sample: 'Escuchar muestra',
  pauseSample: 'Pausar muestra',
  sampleHint: 'Escucha el comienzo de la historia',
  sampleEnd: 'Fin de la muestra',
  sampleUnavailable: 'No se pudo reproducir la muestra.',
  yourWalk: 'Tu paseo',
  allWalks: 'Todos los paseos',
  start: 'Empezar el paseo',
  resume: 'Continuar el paseo',
  estimated: 'Duración estimada',
  audioTime: 'de audio',
  walkingTime: 'a pie',
  durationPending: 'A tu ritmo',
  route: 'Recorrido',
  firstStop: 'Punto de inicio',
  showStops: 'Ver todas las paradas',
  fewerStops: 'Ver menos',
  audioAndText: 'Audio y texto',
  about: 'Antes de salir',
  empty: 'Todavía no hay paseos disponibles en este idioma.',
  clear: 'Ver todos los paseos',
  more: 'Ver más paseos',
  photoCredits: 'Créditos de la foto',
  noPhoto: 'Una historia por descubrir',
  loading: 'Cargando tu paseo…',
  loadError: 'No se pudo cargar el paseo.',
  next: 'Después, sigue hacia',
  overview: 'El paseo',
  speed: 'Velocidad de reproducción',
  finish: 'Volver a los paseos',
  read: 'Leer',
  look: 'Mirar',
  pauseHint: 'Pausa cuando quieras. La ciudad puede esperar.',
  sampleNotice: 'Muestra de hasta 45 segundos',
  safetyHeading: 'A tu ritmo, con cuidado',
  startHint: 'Puedes pausar y retomar la escucha cuando quieras.',
  tourStory: 'Historias de ciudad',
};

const en: Record<keyof typeof es, string> = {
  heading: 'The city has a lot to tell you.',
  intro: 'Pick a walk. Put on your headphones. Discover what usually goes unnoticed.',
  search: 'Where do you want to walk?',
  featured: 'One city, another view',
  allCities: 'All',
  cities: 'Available cities',
  walkingTour: 'Audio walking tour',
  sample: 'Play sample',
  pauseSample: 'Pause sample',
  sampleHint: 'Listen to the beginning of the story',
  sampleEnd: 'End of sample',
  sampleUnavailable: 'The sample could not be played.',
  yourWalk: 'Your walk',
  allWalks: 'All walks',
  start: 'Start the walk',
  resume: 'Resume the walk',
  estimated: 'Estimated duration',
  audioTime: 'of audio',
  walkingTime: 'on foot',
  durationPending: 'At your pace',
  route: 'Route',
  firstStop: 'Starting point',
  showStops: 'View all stops',
  fewerStops: 'Show fewer',
  audioAndText: 'Audio and text',
  about: 'Before you go',
  empty: 'No walks are available in this language yet.',
  clear: 'View all walks',
  more: 'View more walks',
  photoCredits: 'Photo credits',
  noPhoto: 'A story to discover',
  loading: 'Loading your walk…',
  loadError: 'The walk could not be loaded.',
  next: 'Next, head to',
  overview: 'The walk',
  speed: 'Playback speed',
  finish: 'Back to walks',
  read: 'Read',
  look: 'Look',
  pauseHint: 'Pause whenever you like. The city can wait.',
  sampleNotice: 'Sample of up to 45 seconds',
  safetyHeading: 'At your pace, with care',
  startHint: 'You can pause and resume listening whenever you like.',
  tourStory: 'City stories',
};

const fr: Record<keyof typeof es, string> = {
  heading: 'La ville a beaucoup à vous raconter.',
  intro: 'Choisissez une promenade. Mettez vos écouteurs. Découvrez ce qui passe souvent inaperçu.',
  search: 'Où voulez-vous vous promener ?',
  featured: 'Une ville, un autre regard',
  allCities: 'Toutes',
  cities: 'Villes disponibles',
  walkingTour: 'Promenade audio',
  sample: 'Écouter l’aperçu',
  pauseSample: 'Mettre l’aperçu en pause',
  sampleHint: 'Écoutez le début de l’histoire',
  sampleEnd: 'Fin de l’aperçu',
  sampleUnavailable: 'Impossible de lire l’aperçu.',
  yourWalk: 'Votre promenade',
  allWalks: 'Toutes les promenades',
  start: 'Commencer la promenade',
  resume: 'Reprendre la promenade',
  estimated: 'Durée estimée',
  audioTime: 'd’audio',
  walkingTime: 'à pied',
  durationPending: 'À votre rythme',
  route: 'Itinéraire',
  firstStop: 'Point de départ',
  showStops: 'Voir toutes les étapes',
  fewerStops: 'Voir moins',
  audioAndText: 'Audio et texte',
  about: 'Avant de partir',
  empty: 'Aucune promenade n’est encore disponible dans cette langue.',
  clear: 'Voir toutes les promenades',
  more: 'Voir plus de promenades',
  photoCredits: 'Crédits photo',
  noPhoto: 'Une histoire à découvrir',
  loading: 'Chargement de votre promenade…',
  loadError: 'Impossible de charger la promenade.',
  next: 'Ensuite, rendez-vous à',
  overview: 'La promenade',
  speed: 'Vitesse de lecture',
  finish: 'Retour aux promenades',
  read: 'Lire',
  look: 'Regarder',
  pauseHint: 'Mettez en pause quand vous voulez. La ville peut attendre.',
  sampleNotice: 'Aperçu de 45 secondes maximum',
  safetyHeading: 'À votre rythme, avec prudence',
  startHint: 'Vous pouvez mettre en pause et reprendre l’écoute quand vous voulez.',
  tourStory: 'Histoires de ville',
};

const de: Record<keyof typeof es, string> = {
  heading: 'Die Stadt hat viel zu erzählen.',
  intro: 'Wähle einen Spaziergang. Setz deine Kopfhörer auf. Entdecke, was oft übersehen wird.',
  search: 'Wo möchtest du spazieren gehen?',
  featured: 'Eine Stadt, ein anderer Blick',
  allCities: 'Alle',
  cities: 'Verfügbare Städte',
  walkingTour: 'Audio-Spaziergang',
  sample: 'Probe anhören',
  pauseSample: 'Probe pausieren',
  sampleHint: 'Höre dir den Anfang der Geschichte an',
  sampleEnd: 'Ende der Probe',
  sampleUnavailable: 'Die Probe konnte nicht abgespielt werden.',
  yourWalk: 'Dein Spaziergang',
  allWalks: 'Alle Spaziergänge',
  start: 'Spaziergang starten',
  resume: 'Spaziergang fortsetzen',
  estimated: 'Geschätzte Dauer',
  audioTime: 'Audio',
  walkingTime: 'zu Fuß',
  durationPending: 'In deinem Tempo',
  route: 'Route',
  firstStop: 'Startpunkt',
  showStops: 'Alle Haltepunkte anzeigen',
  fewerStops: 'Weniger anzeigen',
  audioAndText: 'Audio und Text',
  about: 'Bevor du losgehst',
  empty: 'In dieser Sprache sind noch keine Spaziergänge verfügbar.',
  clear: 'Alle Spaziergänge anzeigen',
  more: 'Mehr Spaziergänge anzeigen',
  photoCredits: 'Fotocredits',
  noPhoto: 'Eine Geschichte zu entdecken',
  loading: 'Dein Spaziergang wird geladen…',
  loadError: 'Der Spaziergang konnte nicht geladen werden.',
  next: 'Als Nächstes geht es zu',
  overview: 'Der Spaziergang',
  speed: 'Wiedergabegeschwindigkeit',
  finish: 'Zurück zu den Spaziergängen',
  read: 'Lesen',
  look: 'Schauen',
  pauseHint: 'Pausiere, wann du willst. Die Stadt kann warten.',
  sampleNotice: 'Probe von bis zu 45 Sekunden',
  safetyHeading: 'In deinem Tempo, mit Vorsicht',
  startHint: 'Du kannst das Hören jederzeit pausieren und fortsetzen.',
  tourStory: 'Geschichten der Stadt',
};

const it: Record<keyof typeof es, string> = {
  heading: 'La città ha molto da raccontarti.',
  intro: 'Scegli una passeggiata. Metti le cuffie. Scopri ciò che di solito passa inosservato.',
  search: 'Dove vuoi passeggiare?',
  featured: 'Una città, un altro sguardo',
  allCities: 'Tutte',
  cities: 'Città disponibili',
  walkingTour: 'Passeggiata audio',
  sample: 'Ascolta l’anteprima',
  pauseSample: 'Metti in pausa l’anteprima',
  sampleHint: 'Ascolta l’inizio della storia',
  sampleEnd: 'Fine dell’anteprima',
  sampleUnavailable: 'Impossibile riprodurre l’anteprima.',
  yourWalk: 'La tua passeggiata',
  allWalks: 'Tutte le passeggiate',
  start: 'Inizia la passeggiata',
  resume: 'Riprendi la passeggiata',
  estimated: 'Durata stimata',
  audioTime: 'di audio',
  walkingTime: 'a piedi',
  durationPending: 'Al tuo ritmo',
  route: 'Percorso',
  firstStop: 'Punto di partenza',
  showStops: 'Vedi tutte le tappe',
  fewerStops: 'Vedi meno',
  audioAndText: 'Audio e testo',
  about: 'Prima di partire',
  empty: 'Non ci sono ancora passeggiate disponibili in questa lingua.',
  clear: 'Vedi tutte le passeggiate',
  more: 'Vedi altre passeggiate',
  photoCredits: 'Crediti fotografici',
  noPhoto: 'Una storia da scoprire',
  loading: 'Caricamento della tua passeggiata…',
  loadError: 'Impossibile caricare la passeggiata.',
  next: 'Poi, vai verso',
  overview: 'La passeggiata',
  speed: 'Velocità di riproduzione',
  finish: 'Torna alle passeggiate',
  read: 'Leggi',
  look: 'Guarda',
  pauseHint: 'Metti in pausa quando vuoi. La città può aspettare.',
  sampleNotice: 'Anteprima di massimo 45 secondi',
  safetyHeading: 'Al tuo ritmo, con attenzione',
  startHint: 'Puoi mettere in pausa e riprendere l’ascolto quando vuoi.',
  tourStory: 'Storie di città',
};

const translations: Record<Language, Record<keyof typeof es, string>> = {
  es,
  en,
  fr,
  de,
  it,
};

export function mobileTourCopy(language: Language): Record<keyof typeof es, string> {
  return translations[language];
}
