import type { Language } from '@/types/api';

export const privacyCopy = {
  "es": {
    "translationPending": "La información del responsable que aparece a continuación está disponible por ahora en español.",
    "hosting": "Alojamiento",
    "processors": "Proveedores",
    "transfers": "Transferencias internacionales",
    "retention": "Conservación",
    "legalBases": "Finalidades y bases jurídicas",
    "rights": "Ejercicio de derechos",
    "back": "Volver a los tours",
    "title": "Privacidad",
    "progress": "El navegador conserva tu progreso de lectura y escucha en este dispositivo hasta que lo borres. El piloto no necesita cuentas de participantes ni medición publicitaria.",
    "welcome": "Este navegador también recuerda que has visto el aviso de inicio para no repetirlo. La preferencia se queda en este dispositivo hasta que la borres; no activa la ubicación ni la medición de uso.",
    "storageTitle": "Cookies y almacenamiento local",
    "storage": "La cookie tour-page-language recuerda el idioma que eliges durante un año. El almacenamiento local conserva la parada seleccionada (tour-selection), el progreso de lectura y escucha (tour-reading, tour-listening y las claves antiguas tour-progress) y los avisos vistos (tour-notice, tour-welcome), hasta que los borres.",
    "consent": "Tu elección sobre estadísticas (tour-privacy-v1) es válida durante 180 días; después volvemos a preguntarte. Aceptar o rechazar no cambia el acceso a los tours. Puedes cambiarla en cualquier momento desde «Configurar privacidad», al pie de la página. Borrar el progreso no cambia tu elección sobre estadísticas ni el idioma.",
    "locationTitle": "Ubicación, mapas y fotos",
    "photos": "Las fotos se cargan desde Wikimedia. Al establecer esa conexión, el servicio recibe tu dirección IP y la petición de la imagen.",
    "location": "La ubicación es opcional y solo se solicita tras tu acción. Sirve para situarte en el mapa del navegador; el piloto no la envía a su servidor ni guarda tu recorrido. Puedes detener el seguimiento y revocar el permiso en el navegador.",
    "maps": "Mostrar el mapa transmite tu dirección IP y las zonas de mapa solicitadas al proveedor OpenStreetMap. Abrir Google Maps sale de esta aplicación y queda sujeto a las condiciones de Google. El servidor recibe los datos técnicos necesarios para las conexiones y la protección del servicio.",
    "controller": "Responsable",
    "closed": "La prueba permanece cerrada hasta configurar los datos del responsable, los proveedores y la conservación.",
    "analyticsTitle": "Medición opcional (Umami)",
    "analytics": "Si el piloto está configurado con un servidor Umami autoalojado, puede registrar: las visitas, la procedencia de la visita (buscador o canal de campaña), el país aproximado de conexión (no la posición GPS), las interacciones con el tour, el tiempo de lectura estimado, el tiempo de escucha de audio y las valoraciones o comentarios voluntarios. No se usa publicidad ni cuentas de participantes. Con tu permiso se conserva una sesión de medición en esta pestaña, que caduca tras 30 minutos de inactividad o al cerrar la pestaña y se borra al retirar el permiso. No guarda consultas de búsqueda ni direcciones completas de procedencia. Esta medición requiere tu aceptación previa y respeta la señal «No rastrear». Antes de aceptar no se carga el script ni se envían eventos estadísticos. Retirar el permiso detiene los nuevos envíos; no borra los datos ya recibidos. Si el almacenamiento está bloqueado, la medición permanece desactivada.",
    "clear": "Borrar progreso y preferencias",
    "cleared": "Progreso y preferencias borrados en este dispositivo.",
    "clearError": "El navegador no permite borrar los datos."
  },
  "fr": {
    "translationPending": "Les informations du responsable ci-dessous sont actuellement disponibles en espagnol.",
    "hosting": "Hébergement",
    "processors": "Prestataires",
    "transfers": "Transferts internationaux",
    "retention": "Conservation",
    "legalBases": "Finalités et bases juridiques",
    "rights": "Exercice des droits",
    "back": "Retour aux visites",
    "title": "Confidentialité",
    "progress": "Le navigateur conserve votre progression de lecture et d’écoute sur cet appareil jusqu’à son effacement. Aucun compte de participant ni mesure publicitaire n’est nécessaire au pilote.",
    "welcome": "Ce navigateur mémorise aussi que vous avez vu les informations de départ, pour ne pas les répéter. Cette préférence reste sur cet appareil jusqu’à son effacement ; elle n’active ni la localisation ni la mesure d’usage.",
    "storageTitle": "Cookies et stockage local",
    "storage": "La cookie tour-page-language mémorise la langue que vous choisissez pendant un an. Le stockage local conserve la sélection de l’étape (tour-selection), la progression de lecture et d’écoute (tour-reading, tour-listening et les anciennes clés tour-progress), ainsi que les avis consultés (tour-notice, tour-welcome), jusqu’à leur effacement.",
    "consent": "Votre choix de statistiques (tour-privacy-v1) reste valable pendant 180 jours, puis nous vous demandons de choisir à nouveau. Accepter ou refuser ne change pas l’accès aux visites. Vous pouvez modifier ce choix à tout moment dans les paramètres de confidentialité en bas de page. Effacer la progression ne modifie pas votre choix de statistiques ni la langue.",
    "locationTitle": "Position, cartes et photos",
    "photos": "Les photos sont chargées depuis Wikimedia. Ce service reçoit votre adresse IP et la demande de l’image lors de la connexion.",
    "location": "La position est facultative et demandée seulement après votre action. Elle sert à vous situer sur la carte dans le navigateur ; le pilote ne l’envoie pas à son serveur et ne conserve pas votre trajet. Vous pouvez arrêter ce suivi et révoquer l’autorisation dans le navigateur.",
    "maps": "Afficher la carte transmet votre adresse IP et les zones de carte demandées au fournisseur OpenStreetMap. Ouvrir Google Maps quitte cette application et relève des conditions de Google. Le serveur reçoit les données techniques nécessaires aux connexions et à la protection du service.",
    "controller": "Responsable",
    "closed": "L’essai reste fermé jusqu’à la configuration des informations du responsable, des prestataires et de la conservation.",
    "analyticsTitle": "Mesure optionnelle (Umami)",
    "analytics": "Si le pilote est configuré avec un serveur Umami auto-hébergé, il peut enregistrer : les visites, leur provenance (moteur de recherche ou canal de campagne), le pays approximatif de connexion (pas de position GPS), les interactions avec le tour, le temps de lecture estimé, le temps d’écoute audio et les évaluations ou commentaires volontaires. Aucune publicité ni compte de participant n’est utilisé. Avec votre accord, une session de mesure est conservée dans cet onglet ; elle expire après 30 minutes d’inactivité ou à la fermeture de l’onglet et est effacée au retrait de l’accord. Elle ne conserve ni recherches ni adresses complètes de provenance. Cette mesure nécessite votre accord préalable et respecte le signal « Ne pas suivre ». Aucun script ni événement statistique n’est envoyé avant votre accord. Retirer cet accord arrête les nouveaux envois ; cela n’efface pas les données déjà reçues. Si le stockage est bloqué, la mesure reste désactivée.",
    "clear": "Effacer progression et préférences",
    "cleared": "Progression et préférences effacées sur cet appareil.",
    "clearError": "Le navigateur ne permet pas d’effacer les données."
  },
  "en": {
    "translationPending": "The controller information below is currently available in Spanish.",
    "hosting": "Hosting",
    "processors": "Service providers",
    "transfers": "International transfers",
    "retention": "Retention",
    "legalBases": "Purposes and legal bases",
    "rights": "Exercising your rights",
    "back": "Back to tours",
    "title": "Privacy",
    "progress": "Your browser stores your reading and listening progress on this device until you delete it. The pilot does not require participant accounts or advertising measurement.",
    "welcome": "This browser also remembers that you have seen the introduction notice so it does not repeat it. This preference stays on this device until you delete it; it does not enable location access or usage measurement.",
    "storageTitle": "Cookies and local storage",
    "storage": "The tour-page-language cookie remembers your chosen language for one year. Local storage keeps your selected stop (tour-selection), reading and listening progress (tour-reading, tour-listening and legacy tour-progress keys), and notices you have seen (tour-notice, tour-welcome) until you delete them.",
    "consent": "Your statistics choice (tour-privacy-v1) is valid for 180 days; after that, we ask you to choose again. Accepting or rejecting does not change access to tours. You can change your choice at any time using the privacy settings at the bottom of the page. Clearing progress does not change your statistics choice or language.",
    "locationTitle": "Location, maps and photos",
    "photos": "Photos are loaded from Wikimedia. When that connection is made, the service receives your IP address and the image request.",
    "location": "Location is optional and is requested only after you take action. It shows your position on the map in your browser; the pilot does not send it to its server or store your route. You can stop tracking and revoke permission in your browser.",
    "maps": "Displaying the map sends your IP address and the requested map areas to OpenStreetMap. Opening Google Maps takes you outside this app and is subject to Google's terms. The server receives the technical data needed for connections and to protect the service.",
    "controller": "Data controller",
    "closed": "The trial remains closed until the controller, service provider and retention information has been configured.",
    "analyticsTitle": "Optional measurement (Umami)",
    "analytics": "If the pilot is configured with a self-hosted Umami server, it may record page visits, visit source (search engine or campaign channel), approximate connection country (not GPS location), tour interactions, estimated reading time, audio listening time, and voluntary ratings or comments. No advertising or participant accounts are used. With your permission, a measurement session is kept in this tab. It expires after 30 minutes of inactivity or when the tab closes, and is cleared when consent is withdrawn. It does not store search queries or full referring addresses. This measurement requires your prior consent and respects the Do Not Track signal. No statistics script or event is sent before you accept. Withdrawing consent stops new submissions; it does not erase data already received. If storage is blocked, measurement stays disabled.",
    "clear": "Clear progress and preferences",
    "cleared": "Progress and preferences cleared on this device.",
    "clearError": "Your browser does not allow data to be cleared."
  },
  "de": {
    "translationPending": "Die folgenden Angaben des Verantwortlichen sind derzeit auf Spanisch verfügbar.",
    "hosting": "Hosting",
    "processors": "Dienstleister",
    "transfers": "Internationale Datenübermittlungen",
    "retention": "Speicherdauer",
    "legalBases": "Zwecke und Rechtsgrundlagen",
    "rights": "Ausübung Ihrer Rechte",
    "back": "Zurück zu den Touren",
    "title": "Datenschutz",
    "progress": "Ihr Browser speichert Ihren Lese- und Hörfortschritt auf diesem Gerät, bis Sie ihn löschen. Für den Pilotbetrieb sind weder Teilnehmerkonten noch Werbemessung erforderlich.",
    "welcome": "Dieser Browser merkt sich außerdem, dass Sie den Einführungshinweis gesehen haben, damit er nicht erneut angezeigt wird. Diese Einstellung bleibt auf diesem Gerät, bis Sie sie löschen; sie aktiviert weder den Standortzugriff noch die Nutzungsmessung.",
    "storageTitle": "Cookies und lokaler Speicher",
    "storage": "Das Cookie tour-page-language speichert Ihre gewählte Sprache für ein Jahr. Der lokale Speicher bewahrt die ausgewählte Station (tour-selection), den Lese- und Hörfortschritt (tour-reading, tour-listening sowie ältere tour-progress-Schlüssel) und bereits gelesene Hinweise (tour-notice, tour-welcome) auf, bis Sie diese löschen.",
    "consent": "Ihre Entscheidung zur Statistik (tour-privacy-v1) gilt 180 Tage. Danach fragen wir erneut nach Ihrer Entscheidung. Zustimmung oder Ablehnung ändern den Zugang zu den Touren nicht. Sie können Ihre Entscheidung jederzeit über die Datenschutzeinstellungen am Seitenende ändern. Das Löschen des Fortschritts ändert weder Ihre Statistikentscheidung noch die Sprache.",
    "locationTitle": "Standort, Karten und Fotos",
    "photos": "Fotos werden von Wikimedia geladen. Bei dieser Verbindung erhält der Dienst Ihre IP-Adresse und die Bildanfrage.",
    "location": "Die Standortfreigabe ist freiwillig und wird erst nach einer ausdrücklichen Aktion angefragt. Sie zeigt Ihre Position auf der Karte im Browser an; der Pilot übermittelt sie nicht an seinen Server und speichert Ihre Route nicht. Sie können die Standortverfolgung beenden und die Berechtigung im Browser widerrufen.",
    "maps": "Beim Anzeigen der Karte werden Ihre IP-Adresse und die angefragten Kartenausschnitte an OpenStreetMap übermittelt. Beim Öffnen von Google Maps verlassen Sie diese App; es gelten die Bedingungen von Google. Der Server erhält die technischen Daten, die für Verbindungen und den Schutz des Dienstes benötigt werden.",
    "controller": "Verantwortlicher",
    "closed": "Die Testphase bleibt geschlossen, bis die Angaben zum Verantwortlichen, zu den Dienstleistern und zur Speicherdauer eingerichtet sind.",
    "analyticsTitle": "Optionale Nutzungsmessung (Umami)",
    "analytics": "Wenn für den Pilotbetrieb ein selbst gehosteter Umami-Server eingerichtet ist, kann er Seitenaufrufe, die Herkunft des Besuchs (Suchmaschine oder Kampagnenkanal), das ungefähre Verbindungsland (keinen GPS-Standort), Interaktionen mit der Tour, die geschätzte Lesezeit, die Audio-Hörzeit sowie freiwillige Bewertungen oder Kommentare erfassen. Werbung und Teilnehmerkonten werden nicht verwendet. Mit Ihrer Zustimmung wird eine Messsitzung in diesem Tab gespeichert. Sie läuft nach 30 Minuten Inaktivität oder beim Schließen des Tabs ab und wird bei Widerruf gelöscht. Suchanfragen und vollständige Herkunftsadressen werden nicht gespeichert. Diese Messung erfordert Ihre vorherige Zustimmung und berücksichtigt das Do-Not-Track-Signal. Vor Ihrer Zustimmung werden weder Statistikskripte geladen noch Statistikereignisse gesendet. Ein Widerruf beendet neue Übermittlungen; bereits empfangene Daten werden dadurch nicht gelöscht. Ist der Speicher gesperrt, bleibt die Messung deaktiviert.",
    "clear": "Fortschritt und Einstellungen löschen",
    "cleared": "Fortschritt und Einstellungen auf diesem Gerät gelöscht.",
    "clearError": "Ihr Browser erlaubt das Löschen der Daten nicht."
  },
  "it": {
    "translationPending": "Le informazioni del titolare riportate di seguito sono attualmente disponibili in spagnolo.",
    "hosting": "Hosting",
    "processors": "Fornitori di servizi",
    "transfers": "Trasferimenti internazionali",
    "retention": "Conservazione",
    "legalBases": "Finalità e basi giuridiche",
    "rights": "Esercizio dei diritti",
    "back": "Torna ai tour",
    "title": "Privacy",
    "progress": "Il browser conserva i tuoi progressi di lettura e ascolto su questo dispositivo finché non li elimini. Il progetto pilota non richiede account dei partecipanti né misurazioni pubblicitarie.",
    "welcome": "Questo browser ricorda anche che hai visto l'avviso iniziale, per non ripeterlo. Questa preferenza resta sul dispositivo finché non la elimini; non attiva la posizione né la misurazione dell'utilizzo.",
    "storageTitle": "Cookie e archiviazione locale",
    "storage": "Il cookie tour-page-language ricorda la lingua che scegli per un anno. L'archiviazione locale conserva la tappa selezionata (tour-selection), i progressi di lettura e ascolto (tour-reading, tour-listening e le vecchie chiavi tour-progress) e gli avvisi già visualizzati (tour-notice, tour-welcome), finché non li elimini.",
    "consent": "La tua scelta sulle statistiche (tour-privacy-v1) è valida per 180 giorni; poi ti chiediamo di scegliere di nuovo. Accettare o rifiutare non cambia l'accesso ai tour. Puoi modificare la scelta in qualsiasi momento dalle impostazioni sulla privacy in fondo alla pagina. Cancellare i progressi non modifica la scelta sulle statistiche né la lingua.",
    "locationTitle": "Posizione, mappe e foto",
    "photos": "Le foto vengono caricate da Wikimedia. Quando viene stabilita la connessione, il servizio riceve il tuo indirizzo IP e la richiesta dell'immagine.",
    "location": "La posizione è facoltativa e viene richiesta solo dopo una tua azione esplicita. Serve a mostrarti sulla mappa nel browser; il progetto pilota non la invia al proprio server e non conserva il tuo percorso. Puoi interrompere il rilevamento e revocare l'autorizzazione nel browser.",
    "maps": "Visualizzare la mappa trasmette il tuo indirizzo IP e le aree della mappa richieste a OpenStreetMap. Aprire Google Maps significa uscire da questa app ed essere soggetti alle condizioni di Google. Il server riceve i dati tecnici necessari per le connessioni e per proteggere il servizio.",
    "controller": "Titolare del trattamento",
    "closed": "La prova rimane chiusa finché non sono configurate le informazioni sul titolare, sui fornitori e sulla conservazione.",
    "analyticsTitle": "Misurazione facoltativa (Umami)",
    "analytics": "Se il progetto pilota è configurato con un server Umami autogestito, può registrare le visite alle pagine, la provenienza della visita (motore di ricerca o canale della campagna), il paese approssimativo di connessione (non la posizione GPS), le interazioni con il tour, il tempo di lettura stimato, il tempo di ascolto audio e le valutazioni o i commenti volontari. Non vengono utilizzati pubblicità né account dei partecipanti. Con il tuo consenso, una sessione di misurazione viene conservata in questa scheda. Scade dopo 30 minuti di inattività o alla chiusura della scheda e viene cancellata alla revoca del consenso. Non memorizza ricerche né indirizzi completi di provenienza. Questa misurazione richiede il tuo consenso preventivo e rispetta il segnale Do Not Track. Prima del consenso non viene caricato alcuno script statistico né inviato alcun evento statistico. Revocare il consenso interrompe i nuovi invii, ma non elimina i dati già ricevuti. Se l'archiviazione è bloccata, la misurazione rimane disattivata.",
    "clear": "Cancella progressi e preferenze",
    "cleared": "Progressi e preferenze cancellati su questo dispositivo.",
    "clearError": "Il browser non consente di cancellare i dati."
  }
} satisfies Record<Language, Record<string, string>>;
